[k8s_control]
k8s-cp-1 ansible_host=192.168.20.3

[k8s_worker]
k8s-w-1 ansible_host=192.168.20.101
k8s-w-2 ansible_host=192.168.20.102

[k8s:children]
k8s_control
k8s_worker

[k8s:vars]
ansible_user=ops

[db]
pgdb ansible_host=192.168.20.103

[db:vars]
ansible_user=ops
